name: IssueOps Demo Reservation Action
description: Process reservation requests for a fictional business
author: Nick Alteen

branding:
  icon: check-square
  color: blue

inputs:
  action:
    description: The action to take (`init`, `submit`, or `cancel`).
    required: true
  github_token:
    description: The GitHub token to use for interacting with the GitHub API.
    required: true
    default: ${{ github.token }}
  issue_body:
    description:
      The issue body as a JSON string. This is typically the output of the
      `issue-ops/parser` action.
    required: false
  issue_template_path:
    description:
      Path to the issue template file from the root of the repository (e.g.
      `.github/ISSUE_TEMPLATE/reservation.yml`).
    required: true
  project_number:
    description: The number of the project board where reservations are managed.
    required: true
  workspace:
    description:
      The path where the repository has been cloned using the `actions/checkout`
      step. This is required to find the issue form template file.
    required: true
    default: ${{ github.workspace }}

outputs:
  json:
    description: The parsed issue as a JSON string

runs:
  using: node20
  main: dist/index.js
